### ISSUE TITLE
Couldn't make it run

### ISSUE THREAD

**Issue by davejack1** [liabru/dat-gui-light-theme#2]
I put the `dat-gui-light-theme.css` file in my root folder and then added the following line into my html file

`<link href="dat-gui-light-theme.css" rel="stylesheet" type="text/css">`

However, I still see the default theme of datGUI.

Is there any thing extra that I have to do?

**Comment by liabru** [comment]
Hmm you can see it working on my [fractal gears](http://brm.io/gears/) where I seemed to have prepended `body` to every selector, I guess this might actually be necessary then, try using this [css file](http://brm.io/gears/gui-theme.css) instead and see if it works.

**Comment by davejack1** [comment]
Thank you. That worked well.

**Comment by mauro1998** [comment]
Great, thank you.
If anybody wants grey folder arrows instead of white just add:

    // search and replace
    body .dg li.title {
      background: #e8e8e8 url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIUlEQVQI12NgIBYw5ufn/8cQZGBgYECWmDhxIiNcFlkCABvVCJsuKGBHAAAAAElFTkSuQmCC) 6px 10px no-repeat;
    }

    // add
    body .dg .closed li.title {
      background: #e8e8e8 url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAJUlEQVQI12NggIL8/Pz/MDYTAxKASTASVMnAwMAwceJERgZsKgEwpArqRfAIRAAAAABJRU5ErkJggg==) 6px 10px no-repeat;
    }

![screen shot 2018-05-24 at 11 24 39 am](https://user-images.githubusercontent.com/20090908/40498615-1d5087e0-5f45-11e8-8b1f-fed5b511fae8.png)
